name: "Hello .NET"

on:
  workflow_dispatch:

env:
  NOTES_API_TEST_PATH: Notes.Api.Test/Notes.Api.Test.csproj

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "Setup .NET Core SDK"
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.x"

      - name: "Print .NET CLI version"
        run: dotnet --version

      - name: "Restore Notes.Api.Test"
        run: dotnet restore $NOTES_API_TEST_PATH
      
      - name: "Build Notes.Api.Test"
        run: dotnet build --no-restore --configuration Release $NOTES_API_TEST_PATH

      - name: "Run tests in Notes.Api.Test"
        run: dotnet test --no-build --configuration Release --verbosity normal --logger trx $NOTES_API_TEST_PATH